### ISSUE TITLE
Popisek repozitáře

### ISSUE THREAD

**Issue by janpecha** [Tharos/LeanMapper#128]
@Tharos ahoj, mohl bys prosím upravit popisek repozitáře z

> Lean Mapper is a tiny ORM based on powerful dibi database abstraction library for PHP 5.

na

> Lean Mapper is a tiny ORM based on powerful Dibi database abstraction library for PHP.

Ať to slovíčko "PHP 5" zbytečně nemate :)

Díky!

**Comment by Tharos** [comment]
Hotov. :)
