### ISSUE TITLE
Drop support for obsolete PHP versions

### ISSUE THREAD

**Issue by dakujem** [Tharos/LeanMapper#138]
- PHP 5.4
- PHP 5.5

http://php.net/supported-versions.php

Resons for the change:
- prevents using new language constructs

**Comment by janpecha** [comment]
Thanks, I plan it for Lean Mapper 4.x

**Comment by dakujem** [comment]
Which versions of PHP will 4.x support?

**Comment by janpecha** [comment]
I plan PHP 7.1+ (because Dibi 4.x requires PHP 7.1+)

**Comment by dakujem** [comment]
As will Nette 3.x ... I had the feeling. Thanks.
