### ISSUE TITLE
PHP 7.4 compatibility release

### ISSUE THREAD

**Issue by vojtino** [Tharos/LeanMapper#154]
Hi, please we would like just to ask when you will be releasing a version with PHP 7.4 compatibility. We saw commits to develop regarding the new PHP version.  At least if you could give us some timeline estimate, it would be very helpful. 
Thank you very much.

**Comment by janpecha** [comment]
Hello. Have you any issue on PHP 7.4? Last stable release `3.4.1` should be compatible with PHP 7.4.

In `develep` branch are some commits for next big release `4.0`. There is not any estimate for this next version.

**Comment by vojtino** [comment]
Hi, thank you for the prompt response. Well we have some warnings and notices when running php 7.4. Basically these notices come from dibi, because the `3.4.1` version of lean mapper is requiring version `3` of dibi. I presume this version of dibi is maybe not compatible with php 7.4?

**Comment by vojtino** [comment]
To be more precise:
`Trying to access array offset on value of type null`
`File: .../vendor/dibi/dibi/src/Dibi/Fluent.php:466`
`456:        /**
457:         * Generates parameters for Translator.
458:         * @param  string clause name
459:         * @return array
460:         */
461:        protected function _export($clause = null, $args = [])
462:        {
463:            if ($clause === null) {
464:                $data = $this->clauses;
465:                if ($this->command === 'SELECT' && ($data['LIMIT'] || $data['OFFSET'])) {
466:                    $args = array_merge(['%lmt %ofs', $data['LIMIT'][0], $data['OFFSET'][0]], $args);
467:                    unset($data['LIMIT'], $data['OFFSET']);
468:                }
469:    
470:            } else {`

**Comment by janpecha** [comment]
I see, you are right. Bug is in Dibi, it was fixed in https://github.com/dg/dibi/commit/1db63d81e96540e3d8635c4e42312c81aeef8dfa.

If you can need use PHP 7.4 install Lean Mapper on commit c06199fe622d70a79b24f2495acecadfec7397b0 for now. There are some BC breaks after this commit.

BTW I created roadmap for Lean Mapper 4.0 (#155) - I hope version 4.0 will be released to end of year.

**Comment by vojtino** [comment]
Hi, thank you for your suggestion. It looks like it is working with the commit you proposed. Eagerly waiting for the new release 👍
