### ISSUE TITLE
isType method

### ISSUE THREAD

**Issue by real-antonin** [Tharos/LeanMapper#159]
Hi,

if I want to set `bool` value to property, Leanmapper throw exception.

`Unexpected value type given in property 'property_name' in entity App\EntityName, boolean expected, boolean given.`

It's because you comapare same expresions. Shouldn't there be one `boolean`? :)
https://github.com/Tharos/LeanMapper/blob/ecff3dbd21e7230284b9967e674a285efe54989e/src/LeanMapper/Helpers.php#L36

**Comment by janpecha** [comment]
Thanks, fixed :)
