### ISSUE TITLE
Dotaz: Přístup k referenční entitě

### ISSUE THREAD

**Issue by Pechynho** [Tharos/LeanMapper#161]
Ahoj, 

zdědil jsem projekt, kde je toto ORM a narazil jsem na následující problém.

Mám nadefinovanou entitu `Transaction`
```php
 * ...
 * @property PaymentOrder|null $paymentOrder m:hasOne(payment_order_id)
 */
class Transaction extends Entity
{
}
```
Následující kód vyhodí chybu (při ukládání do proměnné `$t`):
```php
$a = new Transaction();
$a->paymentOrder = null;
$t = $a->paymentOrder;
```
Text chyby: 
```
Cannot get value of property 'paymentOrder' in entity App\DAL\Entity\Transaction due to low-level failure: Cannot get referenced Entity for detached Entity.
```

**Comment by Tomac1** [comment]
Ahoj, pokud se nemýlím, tak by entitu $a bylo dobré zapersistovat v repu. 

```
$a = new Transaction();
$a->paymentOrder = null;
$this->transactionRepository->persist($a);
$t = $a->paymentOrder;
```
Díky tomu nebude entita detached, ale attached.

**Comment by Pechynho** [comment]
Úplně na rovinu - snad se nikoho nedotknu - tohle je úplně k ničemu přístup a nepoužitelné ORM. Opravdu nemohu přistoupit k proměnné instance entity, bez toho aniž bych musel bombardovat databázi dotazy?

**Comment by janpecha** [comment]
@Pechynho vydal jsem verzi 4.0.2, ve které by měl tebou uvedený kód fungovat bez vyhození chyby.

**Comment by Pechynho** [comment]
@janpecha Díky, díky za rychlou úpravu
