### ISSUE TITLE
Podpora anotací přes více řádků

### ISSUE THREAD

**Issue by Tharos** [Tharos/LeanMapper#29]
Líbilo by se mi, kdyby se definice libovolné property mohla rozprostírat přes více řádků.

Řekněme, že by výhledově existoval nějaký generátor databázového schéma také nějaká univerzální form factory. Řekněme, že oba tyto nástroje mají 90 % z toho, co potřebují ke své práci znát, už nyní v anotacích u entit. Ale třeba 10 % informací ke svému běhu jim chybí (schema tool by třeba mohl chtít vědět, jak ukládat boolean, factory na formulář by mohla chtít vědět, jakou pokročilou validaci u dané položky použít atp.).

Asi nejčistější by v takovém případě bylo mít těch 10 % doplňujících informací uložených někde samostatně (v nějaký konfiguračních souborech), ale pragmatické je mít i tyto informace v anotacích u Entity.

Anotace jsou teď velmi stručné a to mi maximálně vyhovuje. Pokud by měly narůst, líbilo by se mi, kdyby mohly být přes více řádků:

``` php
<?php

/**
 * @property Book[] $books
 *     m:hasOne
 *     m:filter(order#published)
 *
 * @property int $age
 *     m:form(unsigned, range: 1-99)
 *
 * @property string|null $website
 */
class Author extends Entity
{
}
```

Co si o tom myslíte?

**Comment by castamir** [comment]
V tomto případě jsem spíš pro anotaci nad konkrétními property, podobně jako v drtivé většině frameworků, se kterými jsem se setkal (a to i mimo PHP)

**Comment by janpecha** [comment]
Ať nediskutujeme na 2 místech zároveň.

---

> [castamir](https://github.com/Tharos/LeanMapper/pull/108#issuecomment-286020088): Za mě spíš ne, bude to asi dělat neplechu v komentářích... by default bude veškerý komentář anotací poslední property...

Otázkou je jestli by to skutečně vadilo. Z toho navazujícího komentáře bychom vytáhli jen `m:` příznaky, zbytku komentáře bychom si nevšímali.

Navíc komentáře se obvykle zapisují na začátek phpdocu před veškeré `@anotace`, připadá mi dost nepravděpodobné, že by někdo zapsal komentář na konec a ještě v něm uvedl nějaké `m:` příznaky.

---

Anotace nad property - nad tím jsem taky přemýšlel, docela by se mi to líbilo, akorát ta property by musela být private/protected, aby nad ní mohl LM spouštět __set/__get metody.

**Comment by janpecha** [comment]
Merged #108
