### ISSUE TITLE
Implicitní passThru

### ISSUE THREAD

**Issue by mibk** [Tharos/LeanMapper#45]
Jak již bylo diskutováno [zde](http://forum.nette.org/cs/14592-lean-mapper-tenke-orm-nad-dibi?p=20#p121052), nestálo by za to zvážit implicitní `passThru`?

Má předběžná představa:

``` php
// V mapperu...
public function getImplicitPassThru($propertyType, $entityClass);
```

Co myslíte?

**Comment by janpecha** [comment]
Připravil jsem PR #137 pro implicitní passThru. Pár poznámek:

* metodu v mapperu nejde použít, implicitní passThru si musí obsloužit sama entita
  * detachovaná entita totiž neobsahuje mapper - bylo by hloupé, kdyby v takové situaci implicitní passThru nefungovalo (obejít by se to jistým způsobem dalo, ale i tak by to nefungovalo 100%)
  * navíc z logiky věci nemá mapper co mluvit do toho, jak konkrétní entita transformuje svoje hodnoty (je to její zodpovědnost, ne mapperu)

* dloooouho jsem řešil, jak k tomu řešení přistoupit, variant je totiž ohromné množství (od jednoduchého pole `[PropertyType => passThru]`, přes automatické volání transformačních metod (`DateTime` => `readDateTime`, `writeDateTime`) až po různě komplikované systémy) a každá z variant má svoje nezastupitelné místo, nedá se říct, že by jedna byla správnější než jiná

* nakonec jsem tedy došel k tomu, že nechci vynucovat jeden způsob použití (navíc když žádný není lepší než druhý)

* hledal jsem tedy řešení které bude maximálně flexibilní, jednoduché a nebude nijak výrazně komplikovat kód entity

* nakonec jsem do entity přidal 2 nové protected metody - `decodeRowValue` a `encodeRowValue` (návrh lepších názvů vítán :) ). První metoda je volána hned po přečtení hodnoty z Row, druhá těsně před zápisem do Row

* každý si tak může implicitní passThru nastavit jak potřebuje (pár if-ů, pole v BaseEntitě, automatické volání transformačních metod,...) a není ani problém chování v konkrétních entitách doladit/přetížit

* implicitní a explicitní passThru jsou řetězeny - metody `decodeRowValue` a `encodeRowValue` jsou volány vždy při čtení/zápisu hodnoty z/do Row, následně bude volán uživatelem nastavený passThru, aby hodnoty mohl ještě doladit

* obě nové metody dostanou vždy 2 parametry - `$value` a `LeanMapper\Reflection\Property $property`. Původně jsem místo `$property` předával jen `$type`, ale `$property` obsahuje řadu užitečných informací (`isBasicType`, `containsCollection`,...), které můžou být při transformaci hodnot užitečné (minimálně `isBasicType` určitě). I `$type` by ale bylo dostatečné.

---

Náměty na vylepšení vítány :)

**Comment by mibk** [comment]
Zapomněl jsem, že jsem tuhle feature kdy potřeboval. Lepší názvy mě nenapadají. Já bych tedy tuhle issue klidně pouze pohřbil, ale jestli už to máš napsané a máš pro to využití, tak asi proč ne.

**Comment by janpecha** [comment]
Využití pro to určitě mám - osobně se mi to hodí hlavně při konverzi DB hodnot na objekty a zpět. To využívám poměrně často a je otravné pořád dokola zapisovat `m:passThru` příznaky.

PR jsem mergnul.
