### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by solcik** [Tharos/LeanMapper#51]
Můžu se zeptat, jak to vypadá s dokumentací? .(

**Comment by janpecha** [comment]
Aktuální upravenou dokumentaci lze najít na [webu](http://leanmapper.com/cs/), má i svůj [repozitář](https://github.com/LeanMapper/LeanMapper.github.io) a [issue tracker](https://github.com/LeanMapper/LeanMapper.github.io/issues). Pokud narazíte v dokumentaci na chybu, určitě nám o ní dejte vědět. Stejně tak uvítáme nápady na vylepšení a pull requesty s úpravami :-) Případné dotazy k dokumentaci můžete směřovat také na [Slack](https://pehapkari.slack.com/messages/leanmapper), [Gitter](https://gitter.im/castamir/LeanMapperChat), nebo na [fórum](https://leanmapper-forum.intm.org/).

Považuji tedy toto issue za vyřešené a zavírám ho.
