### ISSUE TITLE
[LeanMapper\Reflection\Property] isWritable = TRUE in BelongsToMany relation

### ISSUE THREAD

**Issue by castamir** [Tharos/LeanMapper#62]
Such property should be IMHO read-only.

**Comment by janpecha** [comment]
Na tohle jsem už taky jednou narazil, připravil jsem návrh změny v PR #124 - kromě `belongsToMany` se jako read-only berou i `belongsToOne` položky.

**Comment by janpecha** [comment]
Merged #124
