### ISSUE TITLE
Změna výchozí hodnoty vazby m:hasOne

### ISSUE THREAD

**Issue by castamir** [Tharos/LeanMapper#77]
V podstatě od zveřejnění LM si nepamatuju situaci, kdy by se mi lišil název property od prvního parametru této vazby. Všechny property s takovou vazbou mají u mě zbytečně dlouhou a opakující se konstrukci:

```
/**
 * @property BaseEntity $ancestor m:hasOne(ancestor)
 * @property BaseEntity $descendant m:hasOne(descendant)
 */
```

Bylo by možné si nastavit výchozí hodnoty u takové vazby? V tomto případě rovnu názvu samotné property?

---

Ještě dodám, že by v takovém případě bylo potřeba propašovat mapper do parseru tak, aby se název property korektně přeložil z např. `myColumn` na `my_column` v závislosti právě na mapperu.

**Comment by castamir** [comment]
Já myslím, že tam není potřeba nic zvláštního vymýšlet... :D

Mám-li např. vazbu 
```php
/**
 * @property Author $author m:hasOne
 * @property Author $anotherAuthor m:hasOne
 */
```

pak bych ocekaval vychozi hodnoty pro nazev sloupce: `author` resp. `another_author` (dle mapovaci konvence field->column, kterou se to stejne prohani jiz nyni) a pro tabulky v obou pripadech `author` (dle mapovani z EntityClass na tabulky)

Ano, bude to BC break, protoze se zmeni vychozi hodnota, ale v praxi tam stejne vsichni maji

```php
/**
 * @property Author $author m:hasOne
 * @property Author $anotherAuthor m:hasOne(another_author)
 */
```

a pokud tam nekdo ma neco jineho, tak ma stejne uplne jiny, svuj vlastni specificky nazev, ktery tam musi ponechat nezavisle na teto zmene, takze se ho to nedotkne...

**Comment by castamir** [comment]
je to BC Break - odlozeno

**Comment by janpecha** [comment]
Jen si tu odložím odkaz na forum, kde se tohle taky kdysi diskutovalo https://forum.dibiphp.com/cs/14592-lean-mapper-tenke-orm-nad-dibi?p=18#p115003

**Comment by janpecha** [comment]
Closed by #149
