### ISSUE TITLE
Nastaveni LeanMaperu v nette neon

### ISSUE THREAD

**Issue by chomenko** [Tharos/LeanMapper#78]
defaultEntityNamespace: 'App\Model' atd..   Nevím zda jsem to nepřehlídl.

**Comment by castamir** [comment]
V nové verzi vzniklo DI extension. Zatím jen se základní funcionalitou - connection settings, profiler a autoregistrace všech Repository tříd

**Comment by castamir** [comment]
V budoucnu plánuji další rozšíření nebo spíš přídání více různých variant DIExtension viz https://github.com/Joseki/LeanMapper-extension/blob/master/src/Joseki/LeanMapper/DI/Extension.php, ze kterého jsem vysekal základ tohoto rozšíření.
