### ISSUE TITLE
new serialization doesn't support multiple connections 

### ISSUE THREAD

**Issue by iinfo-dev-mk** [Tharos/LeanMapper#79]
Entities serialization is supported by Result::enableSerialization() (mentioned [here](https://github.com/Tharos/LeanMapper/commit/88e7e7a0023610782a3f6db33cbf12c6f969e927#commitcomment-7885424)). I don't think it's work for application with multiple repositories from different databases with different server connections. Because only one connection in one static property is presented for whole application. But maybe I missed something.

**Comment by castamir** [comment]
Well, it is not. And I am not sure if it should be resolved on LM side or your. You can use e.g. postgre or sql server type of databases with schemas (multiple databases in a single one). Anyway, hidden connection property is hell in many ways, not just serialization. I am pretty aware of that.

For now, I'm not going to implement this. Feel free to try it by yourself if you want and then send a PR.
