### ISSUE TITLE
problém s kešování - možnost serializovat celý strom entit

### ISSUE THREAD

**Issue by iinfo-dev-mk** [Tharos/LeanMapper#80]
Teď už raději česky. Serializace přidaná v [nedávno](https://github.com/Tharos/LeanMapper/commit/88e7e7a0023610782a3f6db33cbf12c6f969e927) je fajn, ale nedá se moc použít pro ukládání do keší, které ji využívají a což je asi její hlavní využití v leanmapperu.
Problém je v tom, že pokud zakešuji (serializuji) skupinu entit a pak nad nimi někde dále - typicky v šabloně - budu volat nějaké magické property pro získání navázaných entit, tak z principu leanmapperu se budou pokládat další dotazy. Tím ale přicházím o tu výhodu kešování.

Je možné se tomu vyhnout kešováním přímo v šablonách, ale jednak ne vždy to je v šablonách možné a také ne vždy je to vhodné.

Chtělo by to něco, co umí serializovat entitu resp. pole entit i s jejími vazebními entitami a potlačit tak následně paradoxně hlavní benefit leanmapperu - načítání dalších dat až když je potřeba.

**Comment by castamir** [comment]
ve verzi 3.0 bude trida `EntityDataDecoder`, jez muze byt ukazkou, jak neceho podobneho dosahnout
