### ISSUE TITLE
Repository + anotace u entity nefunguje

### ISSUE THREAD

**Issue by JanSuchanek** [Tharos/LeanMapper#83]
/**
 * @table my_book
 * @entity MyBook
 */

Skrze repository se vytvoří My_book entity, je to chyba nebo je zapsaná anotace blbě?

**Comment by mibk** [comment]
Já mám pocit, že tyto anotace již moc nefungují. Možná tak jedna a jen za nějakých okolností. Možná se ale pletu, už si to přesně nepamatuji, protože jsem je nikdy nepoužíval. Takovéhle věci se řeší přes **[Mapper](https://github.com/Tharos/LeanMapper/wiki/entity)**, pokud tedy neznáš. Podívej se i [sem](https://github.com/Tharos/LeanMapper/wiki/camelcase-to-under-score-mapper), aby převod z under_score na CamelCase byl automatický pro všechny entity.
