### ISSUE TITLE
Firebird - nazvy sloupců velkými písmeny

### ISSUE THREAD

**Issue by JanGalek** [Tharos/LeanMapper#99]
Zdravím,
ať se snažím jak chci, stále dostávám chybovou hlášku, že column id missing, což je pravda, jelikož firebird  hází názvy sloupců na velká písmena. Šlo by to nějak obejít ? 

Při nejlepší si nastavit Identifikátor (db jsem netvořil celou, jen z části a id jsou tam tak různě.

Prozatím jsem si vytvořil vlastní mapper
```
<?php
namespace LeanMapper;

use LeanMapper\Exception\InvalidStateException;

class FirebirdMapper extends DefaultMapper implements IMapper
{
	/*
	 * @inheritdoc
	 */
	public function getPrimaryKey($table)
	{
		return 'ID';
	}

	/*
	 * @inheritdoc
	 */
	public function getPrimaryKeyTable($table)
	{
		return 'OID$' . $table;
	}
}
```

**Comment by janpecha** [comment]
Co si vytvořit vlastní [mapper](http://leanmapper.github.io/cs/docs/mapper/), který by názvy sloupců převáděl na velká písmena a tak by napověděl LM, jaký sloupec má hledat?

**Comment by JanGalek** [comment]
tím jsem to vyřešil, jen jsem myslel, jestli na to není nějaká anotace :)

**Comment by castamir** [comment]
Ne, není. K mapování slouží mapper ;)

Každopádně používání case-sensitive databáze obecně moc nedoporučuju. Nevidím v tom žádný přínos, jen komplikace...

**Comment by janpecha** [comment]
Zavírám jako vyřešené. Kdyby bylo potřeba, znovu issue otevři, nebo napiš na [Slack](https://pehapkari.slack.com/messages/leanmapper), [Gitter](https://gitter.im/castamir/LeanMapperChat), nebo na [fórum](https://leanmapper-forum.intm.org/).
